sudo: required

service: docker

language: ruby
rvm:
  - 2.4.3

env:
  matrix:
    - INSTANCE=noschedule-ubuntu-1404
    - INSTANCE=noschedule-ubuntu-1604
    - INSTANCE=noschedule-ubuntu-1804
    - INSTANCE=schedule-ubuntu-1404
    - INSTANCE=schedule-ubuntu-1604
    - INSTANCE=schedule-ubuntu-1804

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )

install: bundle --jobs=3 --retry=3
cache:
  directories:
    - vendor/bundle

script:
  - INSTANCE=$INSTANCE make travis

before_deploy:
- mkdir ~/chef
- openssl aes-256-cbc -K $encrypted_02ba4c0f2d2e_key -iv $encrypted_02ba4c0f2d2e_iv -in .travis/majormoses.pem.enc -out .travis/majormoses.pem -d
- rvm $(travis_internal_ruby) --fuzzy do gem install semver2 -v '~> 3.4'

# when we are unblocked by: https://github.com/travis-ci/dpl/issues/841
deploy:
  edge: true
  provider: chef-supermarket
  user_id: majormoses
  client-key: .travis/majormoses.pem
  cookbook_category: Others
  on:
    tags: true
